-- index
CREATE TABLE EMPLOYEES4 AS SELECT * FROM EMPLOYEES e ;

SELECT 	rowid, EMPLOYEE_ID 
FROM 	EMPLOYEES4 e
--WHERE 	EMPLOYEE_ID = 200
;
SELECT * FROM EMPLOYEES4 ORDER BY EMPLOYEE_ID ;

INSERT INTO EMPLOYEES4 (employee_id, FIRST_NAME, LAST_NAME)
VALUES (100, 'Steven', 'King')
;

CREATE UNIQUE INDEX idx_employee3_id 
ON EMPLOYEES4(employee_id);

DELETE FROM EMPLOYEES4 e 
WHERE 	FIRST_NAME = 'Steven'
AND 	EMAIL IS NULL 
;

SELECT * FROM EMPLOYEES4 WHERE EMPLOYEE_ID = 100;

CREATE INDEX idx_employee4_name 
ON EMPLOYEES4(first_name);

