SELECT * FROM EMPLOYEES e ;

SELECT  SUM(SALARY), AVG(SALARY),min(SALARY), MAX(SALARY) 
FROM 	EMPLOYEES e 
WHERE 	JOB_ID LIKE 'SA%'
;

SELECT  JOB_ID, SUM(SALARY), AVG(SALARY),min(SALARY), MAX(SALARY) 
FROM 	EMPLOYEES e 
WHERE 	JOB_ID LIKE 'SA%'
GROUP BY JOB_ID 
;

SELECT 	*
FROM 	EMPLOYEES e  
;

SELECT 	*
FROM 	DEPARTMENTS d 
;

-- inner join
SELECT 	e.FIRST_NAME , e.LAST_NAME , e.DEPARTMENT_ID ,
		d.DEPARTMENT_ID , d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID  = d.DEPARTMENT_ID 
ORDER BY e.FIRST_NAME 
;

SELECT * FROM DEPARTMENTS d ;
SELECT * FROM LOCATIONS l ;


SELECT  * 
FROM 	DEPARTMENTS d 
;

SELECT 	*
FROM 	LOCATIONS l 
;

SELECT 	d.DEPARTMENT_ID , d.DEPARTMENT_NAME ,
		l.LOCATION_ID , l.CITY 
FROM 	DEPARTMENTS d 
 	INNER JOIN LOCATIONS l 
 	ON d.LOCATION_ID  = l.LOCATION_ID 
;


SELECT  e.FIRST_NAME , 
		e.LAST_NAME , 
		e.DEPARTMENT_ID, 
		d.DEPARTMENT_NAME , 
		d.LOCATION_ID, 
		l.CITY,
		j.JOB_ID, 
		j.JOB_TITLE 
FROM 	EMPLOYEES e
	INNER JOIN DEPARTMENTS d 
	ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
	INNER JOIN LOCATIONS l 
	ON d.LOCATION_ID = l.LOCATION_ID
	INNER JOIN JOBS j 
	ON e.JOB_ID  = j.JOB_ID 
WHERE l.CITY = 'Seattle'
;

SELECT * FROM JOB_HISTORY
WHERE 	EMPLOYEE_ID  = 200
;

-- 107
SELECT count(*) FROM EMPLOYEES;

-- 110
-- left outer join 
SELECT 	e.EMPLOYEE_ID , e.FIRST_NAME , e.HIRE_DATE ,
		jh.START_DATE , jh.END_DATE , jh.JOB_ID , jh.DEPARTMENT_ID 
FROM 	EMPLOYEES e 
 LEFT OUTER JOIN JOB_HISTORY jh 
 ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID 
 --WHERE e.EMPLOYEE_ID = 200
;

-- 10
SELECT 	e.EMPLOYEE_ID , e.FIRST_NAME , e.HIRE_DATE ,
		jh.START_DATE , jh.END_DATE , jh.JOB_ID , jh.DEPARTMENT_ID 
FROM 	EMPLOYEES e 
 inner JOIN JOB_HISTORY jh 
 ON e.EMPLOYEE_ID = jh.EMPLOYEE_ID 
;

-- 문제 1 : 사원들의 이름(EMPLOYEES), 
-- 부서번호(EMPLOYEES,DEPARTMENTS), 부서명(DEPARTMENTS)을 출력
-- 부서번호가 존재하는 사원 정보로 조회하기

SELECT  e.FIRST_NAME , e.DEPARTMENT_ID , d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e 
	INNER JOIN DEPARTMENTS d 
	ON	e.DEPARTMENT_ID  = d.DEPARTMENT_ID 
;

SELECT  e.FIRST_NAME , e.DEPARTMENT_ID , d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e 
	LEFT OUTER  JOIN DEPARTMENTS d 
	ON	e.DEPARTMENT_ID  = d.DEPARTMENT_ID 
;

SELECT * FROM EMPLOYEES e  WHERE FIRST_NAME  = 'Kimberely';








